services:

  # SSL CERTIFICATE GEN (FOR NGINX LOCAL DEV)
  cert-generator:
    image: ${CERTGEN_IMAGE}
    environment:
      - SSL_SUBJECT=localhost
      - SSL_EXPIRE=365
      - SSL_KEY=active.key
      - SSL_CERT=active.crt
    volumes:
      - certs_data:/certs

  # FASTAPI
  backend:
    build: ./backend/
    ports:
      - "${BACKEND_PORT}:8000"
    volumes:
      - ./backend/app/:/app
    command: sh -c 'fastapi dev main.py --host 0.0.0.0 --port 8000'

  # DB
  postgres:
    image: ${POSTGRES_IMAGE}
    restart: always
    shm_size: 128mb
    volumes:
      - postgres-data:/var/lib/postgresql
    environment:
      POSTGRES_USER: ${POSTGRES_ADMIN}
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_PASSWORD: ${POSTGRES_ADMIN_PASSWORD}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      retries: 5
      start_period: 30s
      timeout: 10s

  # DB MANAGER
  adminer:
    image: ${ADMINER_IMAGE}
    restart: always
    ports:
      - "${ADMINER_PORT}:8080"
  
  # LOGIN API
  zitadel-api:
    image: ghcr.io/zitadel/zitadel:${ZITADEL_VERSION}
    restart: unless-stopped
    user: "0"
    command: start-from-init --masterkey "${ZITADEL_MASTERKEY}"
    environment:
      ZITADEL_PORT: ${ZITADEL_PORT}
      ZITADEL_EXTERNALDOMAIN: ${ZITADEL_DOMAIN}
      ZITADEL_EXTERNALPORT: ${ZITADEL_EXTERNALPORT}
      ZITADEL_EXTERNALSECURE: ${ZITADEL_EXTERNALSECURE}
      ZITADEL_TLS_ENABLED: false

      ZITADEL_DATABASE_POSTGRES_DSN: "postgresql://${POSTGRES_ADMIN}:${POSTGRES_ADMIN_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable"

      ZITADEL_FIRSTINSTANCE_ORG_HUMAN_PASSWORDCHANGEREQUIRED: false
      ZITADEL_FIRSTINSTANCE_LOGINCLIENTPATPATH: /zitadel/bootstrap/login-client.pat
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_USERNAME: login-client
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_MACHINE_NAME: Automatically Initialized IAM_LOGIN_CLIENT
      ZITADEL_FIRSTINSTANCE_ORG_LOGINCLIENT_PAT_EXPIRATIONDATE: ${LOGIN_CLIENT_PAT_EXPIRATION}

      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_REQUIRED: true
      ZITADEL_DEFAULTINSTANCE_FEATURES_LOGINV2_BASEURI: ${ZITADEL_PUBLIC_SCHEME}://${ZITADEL_DOMAIN}/ui/v2/login/
      ZITADEL_OIDC_DEFAULTLOGINURLV2: ${ZITADEL_PUBLIC_SCHEME}://${ZITADEL_DOMAIN}/ui/v2/login/login?authRequest=
      ZITADEL_OIDC_DEFAULTLOGOUTURLV2: ${ZITADEL_PUBLIC_SCHEME}://${ZITADEL_DOMAIN}/ui/v2/login/logout?post_logout_redirect=
      ZITADEL_SAML_DEFAULTLOGINURLV2: ${ZITADEL_PUBLIC_SCHEME}://${ZITADEL_DOMAIN}/ui/v2/login/login?samlRequest=

      ZITADEL_LOGSTORE_ACCESS_STDOUT_ENABLED: ${ZITADEL_ACCESS_LOG_STDOUT_ENABLED}

    healthcheck:
      test:
        - CMD
        - /app/zitadel
        - ready
      interval: 10s
      timeout: 30s
      retries: 12
      start_period: 20s
    volumes:
      - zitadel-bootstrap:/zitadel/bootstrap:rw
    depends_on:
      postgres:
        condition: service_healthy

  # LOGIN FRONT
  zitadel-login:
    image: ghcr.io/zitadel/zitadel-login:${ZITADEL_VERSION}
    restart: always
    user: "0"
    environment:
      ZITADEL_API_URL: http://zitadel-api:8160
      NEXT_PUBLIC_ZITADEL_API_URL: https://${ZITADEL_DOMAIN}
      NEXT_PUBLIC_BASE_PATH: /ui/v2/login
      ZITADEL_SERVICE_USER_TOKEN_FILE: /zitadel/bootstrap/login-client.pat
      CUSTOM_REQUEST_HEADERS: "Host: ${ZITADEL_DOMAIN}, X-Forwarded-Proto: https, X-Forwarded-Host: ${ZITADEL_DOMAIN}, X-Forwarded-Port: 443"

    healthcheck:
      test:
        - CMD
        - /bin/sh
        - -c
        - node ./healthcheck.mjs http://localhost:3000/ui/v2/login/healthy
      interval: 10s
      timeout: 30s
      retries: 12
      start_period: 20s
    volumes:
      - zitadel-bootstrap:/zitadel/bootstrap:ro
    depends_on:
      zitadel-api:
        condition: service_healthy
  
  # PROXY (FOR DEV)
  nginx-proxy:
    image: ${NGINX_IMAGE}
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - certs_data:/etc/certs:ro
      - nginx-proxy-manager_letsencrypt:/etc/letsencrypt
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      zitadel-api:
        condition: service_healthy
      zitadel-login:
        condition: service_healthy
      postgres:
        condition: service_healthy

volumes:
  postgres-data:
  zitadel-bootstrap:
  nginx-proxy-manager_letsencrypt:
  certs_data:
