"""new position attribute in task

Revision ID: 041e7d56b3c0
Revises: 4013868ff98f
Create Date: 2026-10-06 13:20:12.551689

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '041e7d56b3c0'
down_revision: Union[str, Sequence[str], None] = '4013868ff98f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('notifications')
    op.drop_constraint(op.f('comments_sender_id_fkey'), 'comments', type_='foreignkey')
    op.drop_column('comments', 'sender_id')
    op.add_column('tasks', sa.Column('position', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'position')
    op.add_column('comments', sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False))
    op.create_foreign_key(op.f('comments_sender_id_fkey'), 'comments', 'users', ['sender_id'], ['id'])
    op.create_table('notifications',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('type', postgresql.ENUM('WORKSPACE_INVITE', 'TASK_ASSIGNMENT', 'COMMENT_MENTION', 'ASSIGNEE_COMMENT', name='notification_type_enum'), autoincrement=False, nullable=False),
    sa.Column('type_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('sender_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('recipient_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_test', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('notifications_pkey'))
    )
    # ### end Alembic commands ###
