"""add new Status model

Revision ID: 41c0e1539085
Revises: 77aafc520b3b
Create Date: 2026-09-29 12:11:20.035358

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '41c0e1539085'
down_revision: Union[str, Sequence[str], None] = '77aafc520b3b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('statuses',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('project_id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['project_id'], ['projects.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('tasks', sa.Column('status_id', sa.Uuid(), nullable=True))
    op.create_foreign_key(None, 'tasks', 'statuses', ['status_id'], ['id'], ondelete='SET NULL')
    op.drop_column('tasks', 'status')
    # 2. Preenche os usuários existentes
    op.execute("""
        UPDATE users
        SET nickname = COALESCE(name, 'Usuário')
        WHERE nickname IS NULL
    """)
    op.execute("UPDATE users SET bio = '' WHERE bio IS NULL")

    op.alter_column(
        "users",
        "bio",
        existing_type=sa.String(length=300),
        nullable=False,
    )

    # 3. Torna a coluna obrigatória
    op.alter_column(
        "users",
        "nickname",
        existing_type=sa.String(length=100),
        nullable=False,
    )
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'profile_picture',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # 1. Cria a coluna permitindo NULL inicialmente

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'profile_picture',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'bio',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'nickname',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('tasks', sa.Column('status', postgresql.ENUM('PENDING', 'DONE', name='task_status_enum'), server_default=sa.text("'PENDING'::task_status_enum"), autoincrement=False, nullable=False))
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.drop_column('tasks', 'status_id')
    op.drop_table('statuses')
    # ### end Alembic commands ###
