"""add cascade delete

Revision ID: 59d709e1d1e3
Revises: 
Create Date: 2026-09-24 14:40:36.532822

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '59d709e1d1e3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('lists_project_id_fkey'), 'lists', type_='foreignkey')
    op.create_foreign_key(None, 'lists', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('projects_workspace_id_fkey'), 'projects', type_='foreignkey')
    op.create_foreign_key(None, 'projects', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.add_column('tags', sa.Column('project_id', sa.Uuid(), nullable=False))
    op.create_foreign_key(None, 'tags', 'projects', ['project_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint(op.f('task_assignees_task_id_fkey'), 'task_assignees', type_='foreignkey')
    op.drop_constraint(op.f('task_assignees_user_id_fkey'), 'task_assignees', type_='foreignkey')
    op.create_foreign_key(None, 'task_assignees', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'task_assignees', 'tasks', ['task_id'], ['id'])
    op.create_unique_constraint('uq_task_tag', 'task_tags', ['task_id', 'tag_id'])
    op.drop_constraint(op.f('task_tags_tag_id_fkey'), 'task_tags', type_='foreignkey')
    op.drop_constraint(op.f('task_tags_task_id_fkey'), 'task_tags', type_='foreignkey')
    op.create_foreign_key(None, 'task_tags', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'task_tags', 'tasks', ['task_id'], ['id'], ondelete='CASCADE')
    op.add_column('tasks', sa.Column('task_id', sa.Uuid(), nullable=True))
    op.drop_constraint(op.f('tasks_list_id_fkey'), 'tasks', type_='foreignkey')
    op.create_foreign_key(None, 'tasks', 'lists', ['list_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'tasks', 'tasks', ['task_id'], ['id'])
    op.drop_constraint(op.f('workspace_invites_workspace_id_fkey'), 'workspace_invites', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_invites', 'workspaces', ['workspace_id'], ['id'], ondelete='CASCADE')
    op.drop_index(op.f('uq_workspace_member'), table_name='workspace_members')
    op.create_unique_constraint('uq_workspace_member', 'workspace_members', ['workspace_id', 'user_id'])
    op.drop_constraint(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', type_='foreignkey')
    op.drop_constraint(op.f('workspace_members_user_id_fkey'), 'workspace_members', type_='foreignkey')
    op.create_foreign_key(None, 'workspace_members', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'workspace_members', 'workspaces', ['workspace_id'], ['id'])
    op.alter_column('workspaces', 'logo_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    op.drop_constraint(op.f('workspaces_owner_id_fkey'), 'workspaces', type_='foreignkey')
    op.create_foreign_key(None, 'workspaces', 'users', ['owner_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workspaces', type_='foreignkey')
    op.create_foreign_key(op.f('workspaces_owner_id_fkey'), 'workspaces', 'users', ['owner_id'], ['id'], deferrable=True)
    op.alter_column('workspaces', 'logo_url',
               existing_type=sa.VARCHAR(length=100),
               nullable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workspace_members', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_members_user_id_fkey'), 'workspace_members', 'users', ['user_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('workspace_members_workspace_id_fkey'), 'workspace_members', 'workspaces', ['workspace_id'], ['id'], deferrable=True)
    op.drop_constraint('uq_workspace_member', 'workspace_members', type_='unique')
    op.create_index(op.f('uq_workspace_member'), 'workspace_members', ['workspace_id', 'user_id'], unique=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'workspace_invites', type_='foreignkey')
    op.create_foreign_key(op.f('workspace_invites_workspace_id_fkey'), 'workspace_invites', 'workspaces', ['workspace_id'], ['id'], onupdate='CASCADE', ondelete='CASCADE')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tasks', type_='foreignkey')
    op.create_foreign_key(op.f('tasks_list_id_fkey'), 'tasks', 'lists', ['list_id'], ['id'], deferrable=True)
    op.drop_column('tasks', 'task_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'task_tags', type_='foreignkey')
    op.create_foreign_key(op.f('task_tags_task_id_fkey'), 'task_tags', 'tasks', ['task_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('task_tags_tag_id_fkey'), 'task_tags', 'tags', ['tag_id'], ['id'], deferrable=True)
    op.drop_constraint('uq_task_tag', 'task_tags', type_='unique')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'task_assignees', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'task_assignees', type_='foreignkey')
    op.create_foreign_key(op.f('task_assignees_user_id_fkey'), 'task_assignees', 'users', ['user_id'], ['id'], deferrable=True)
    op.create_foreign_key(op.f('task_assignees_task_id_fkey'), 'task_assignees', 'tasks', ['task_id'], ['id'], deferrable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.drop_column('tags', 'project_id')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.create_foreign_key(op.f('projects_workspace_id_fkey'), 'projects', 'workspaces', ['workspace_id'], ['id'], deferrable=True)
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'lists', type_='foreignkey')
    op.create_foreign_key(op.f('lists_project_id_fkey'), 'lists', 'projects', ['project_id'], ['id'], deferrable=True)
    op.drop_table('books')
    # ### end Alembic commands ###
