"""add unique arguments to task assignee

Revision ID: 77aafc520b3b
Revises: 19d8eb7355af
Create Date: 2026-09-24 17:06:33.022908

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77aafc520b3b'
down_revision: Union[str, Sequence[str], None] = '19d8eb7355af'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_task_assignee', 'task_assignees', ['task_id', 'user_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_task_assignee', 'task_assignees', type_='unique')
    # ### end Alembic commands ###
